apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      nodePort: 30084
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: dummy
          image: alpine
          command: ["sleep", "3600"]